# Generated by Django 2.1.3 on 2018-12-02 21:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zajety', models.BooleanField(verbose_name='Czy zajęty?')),
            ],
            options={
                'verbose_name_plural': 'Apartamenty',
            },
        ),
        migrations.CreateModel(
            name='BonPracowniczy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Bony pracownicze',
            },
        ),
        migrations.CreateModel(
            name='DaneLogowania',
            fields=[
                ('login', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Login')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres mailowy')),
                ('haslo', models.CharField(max_length=255, verbose_name='Hasło')),
            ],
            options={
                'verbose_name_plural': 'Dane logowania',
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=255, verbose_name='Nazwisko')),
                ('adres', models.CharField(max_length=255, verbose_name='Adres zamieszkania')),
                ('numer_karty', models.CharField(max_length=255, verbose_name='Numer karty')),
                ('dane_logowania', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.DaneLogowania')),
            ],
            options={
                'verbose_name_plural': 'Klienci',
            },
        ),
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=255, verbose_name='Ulica')),
                ('kod_pocztowy', models.CharField(max_length=255, verbose_name='Kod pocztowy')),
                ('miasto', models.CharField(max_length=255, verbose_name='Miasto')),
            ],
            options={
                'verbose_name_plural': 'Lokalizacje',
            },
        ),
        migrations.CreateModel(
            name='OpisApartamentu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena')),
                ('lokalizacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Lokalizacja')),
            ],
            options={
                'verbose_name_plural': 'Opisy apartamentów',
            },
        ),
        migrations.CreateModel(
            name='OpisSprzetu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena')),
            ],
            options={
                'verbose_name_plural': 'Opisy sprzętu',
            },
        ),
        migrations.CreateModel(
            name='PotwierdzenieWplaty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kwota')),
                ('data', models.DateField(verbose_name='Data dokonania')),
            ],
            options={
                'verbose_name_plural': 'Potwierdzenia wpłat',
            },
        ),
        migrations.CreateModel(
            name='PotwierdzenieZwrotu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Potwierdzenia zwrotów',
            },
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=255, verbose_name='Nazwisko')),
                ('adres', models.CharField(max_length=255, verbose_name='Adres zamieszkania')),
                ('wyplata', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wypłata')),
                ('dane_logowania', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.DaneLogowania')),
            ],
            options={
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('nazwa', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Producent')),
            ],
            options={
                'verbose_name_plural': 'Producenci',
            },
        ),
        migrations.CreateModel(
            name='Rabat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procent_znizki', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(100)], verbose_name='Procent zniżki')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Klient')),
            ],
            options={
                'verbose_name_plural': 'Rabaty',
            },
        ),
        migrations.CreateModel(
            name='RezerwacjaSprzetu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField(verbose_name='Data wypożyczenia')),
                ('data_zwrotu', models.DateField(verbose_name='Data zwrotu')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Klient')),
            ],
            options={
                'verbose_name_plural': 'Rezerwacje sprzętu',
            },
        ),
        migrations.CreateModel(
            name='RezerwacjeApartamentow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wynajecia', models.DateField(verbose_name='Data wynajęcia')),
                ('data_wymeldowania', models.DateField(verbose_name='Data wymeldowania')),
                ('apartament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Apartament')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Klient')),
            ],
            options={
                'verbose_name_plural': 'Rezerwacje apartamentów',
            },
        ),
        migrations.CreateModel(
            name='RodzajApartamentu',
            fields=[
                ('nazwa', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Rodzaj apartamentu')),
            ],
            options={
                'verbose_name_plural': 'Rodzaje apartamentów',
            },
        ),
        migrations.CreateModel(
            name='RodzajSprzetu',
            fields=[
                ('nazwa', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Rodzaj sprzętu')),
            ],
            options={
                'verbose_name_plural': 'Rodzaje sprzętu',
            },
        ),
        migrations.CreateModel(
            name='Sprzet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rozmiar', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rozmiar')),
                ('termin_przegladu', models.DateTimeField(verbose_name='Termin przeglądu')),
                ('zajety', models.BooleanField(verbose_name='Czy zajęty?')),
                ('opis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.OpisSprzetu')),
            ],
            options={
                'verbose_name_plural': 'Sprzęt',
            },
        ),
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('nazwa', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Stanowisko')),
            ],
            options={
                'verbose_name_plural': 'Stanowiska',
            },
        ),
        migrations.CreateModel(
            name='TypBonuPracowniczego',
            fields=[
                ('nazwa', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Typ')),
            ],
            options={
                'verbose_name_plural': 'Typy bonów pracowniczych',
            },
        ),
        migrations.CreateModel(
            name='TypRabatu',
            fields=[
                ('typ', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Typy rabatu')),
            ],
            options={
                'verbose_name_plural': 'Typy rabatów',
            },
        ),
        migrations.AddField(
            model_name='rezerwacjasprzetu',
            name='sprzet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Sprzet'),
        ),
        migrations.AddField(
            model_name='rabat',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.TypRabatu'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='stanowisko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Stanowisko'),
        ),
        migrations.AddField(
            model_name='potwierdzeniezwrotu',
            name='pracownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Pracownik'),
        ),
        migrations.AddField(
            model_name='opissprzetu',
            name='producent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Producent'),
        ),
        migrations.AddField(
            model_name='opissprzetu',
            name='rodzaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.RodzajSprzetu'),
        ),
        migrations.AddField(
            model_name='opisapartamentu',
            name='rodzaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.RodzajApartamentu'),
        ),
        migrations.AddField(
            model_name='bonpracowniczy',
            name='stanowisko',
            field=models.ManyToManyField(to='hotel.Stanowisko'),
        ),
        migrations.AddField(
            model_name='bonpracowniczy',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.TypBonuPracowniczego'),
        ),
        migrations.AddField(
            model_name='apartament',
            name='opis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.OpisApartamentu'),
        ),
    ]
