# Generated by Django 2.1.3 on 2018-12-09 20:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potwierdzeniewplaty',
            name='rezerwacja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potwierdzenie_wplaty', to='hotel.RezerwacjeApartamentow'),
        ),
        migrations.AddField(
            model_name='potwierdzeniezwrotu',
            name='rezerwacja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potwierdzenie_zwrotu', to='hotel.RezerwacjeApartamentow'),
        ),
        migrations.AlterField(
            model_name='rabat',
            name='procent_znizki',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Procent zniżki'),
        ),
    ]
