# Generated by Django 2.1.3 on 2018-12-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20181209_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potwierdzeniewplaty',
            name='rezerwacja',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='potwierdzenie_wplaty', to='hotel.RezerwacjeApartamentow'),
        ),
        migrations.AlterField(
            model_name='potwierdzeniezwrotu',
            name='rezerwacja',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='potwierdzenie_zwrotu', to='hotel.RezerwacjeApartamentow'),
        ),
    ]
