from .login import LoginPage
from .klient_home import KlientPage
from .pracownik_home import PracownikPage
from .register_form import RegisterPage
from .register_pracownik import RegisterPrac
from .register_klient import RegisterKli
from .add_apartment import ApartmentAddPage
from .add_apartment_description import AddApartmentDescription
from .add_item import ItemAddPage
from .add_item_description import AddItemDescription
from .reserve_apartment import ApartmentReservePage
from .klient_change_page import KlientChangePage
from .reserve_item import ItemReservePage
from .pracownik_change_page import PracownikChangePage